FROM golang:latest
COPY docker/start.sh /
ENV  GOPROXY=https://goproxy.io
ENV  APPLICATION_MYSQL_HOST='localhost'
ENV  APPLICATION_MYSQL_PORT="3306"
ENV  APPLICATION_MYSQL_USERNAME="root"
ENV  APPLICATION_MYSQL_PASSWORD=""
ENV  APPLICATION_REDIS_HOST="localhost:6379"
ENV  APPLICATION_REDIS_PASSWORD=""
ENV  APPLICATION_LOG_ID="repository"
ENV  APPLICATION_LOG_INSTANCE_ID="main-service"
ENV  APPLICATION_LOG_HOST="http://localhost:6000"
ENV  APPLICATION_MAIL_USERNAME=""
ENV  APPLICATION_MAIL_PASSWORD=""
ENV  APPLICATION_MAIL_HOST=""
ENV  APPLICATION_MAIL_ADDRESS=""
ENV  APPLICATION_MQ_URL="amqp://localhost:5672/"
RUN mkdir /go/app
ADD . /go/app
WORKDIR /go/app
RUN go build -o main .
ENTRYPOINT ["sh","/start.sh"]
