version: '2'
services:
  yougame-repository:
    build:
      context: .
    ports:
      - "6969:8888"
    environment:
      APPLICATION_MYSQL_HOST : yougame_db
      APPLICATION_MYSQL_PORT : "3306"
      APPLICATION_LOG_HOST: "http://logstash:6000"
    networks:
      - docker-elk_elk
      - database_default
      - compose_api
networks:
  database_default:
    external: true
  docker-elk_elk:
    external: true
  compose_api:
    external: true
